/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package piano;

import org.junit.Test;
import static org.junit.Assert.*;

import org.junit.Before;

public class BlockTest {
    private Block b;

    @Before
    public void init() {
        b = new Block(61, 76, null, null);
    }

    @Test
    public void activeTest() {
        assertFalse(b.isActive());
        b.update();
        assertTrue(b.isActive());
        b.update();
        assertFalse(b.isActive());
    }

    @Test
    public void getTest() {
        assertEquals(61, b.getX());
        assertEquals(76, b.getY());
        assertEquals(null, b.getSound());
        b.setStatus(true);
        assertTrue(b.isActive());
    }
    
}
